#!/bin/bash

mount | grep -q '/local/screencapt/proc' || mount -o bind /proc /local/screencapt/proc
mount | grep -q '/local/screencapt/dev' || mount -o bind /dev /local/screencapt/dev
mount | grep -q '/local/screencapt/dev/shm' || mount -t tmpfs shm /local/screencapt/dev/shm
mount | grep -q '/local/screencapt/usr/portage' || mount -o bind /usr/portage /local/screencapt/usr/portage
mount | grep -q '/local/screencapt/local/portage/overlay' || mount -o bind /local/portage/overlay /local/screencapt/local/portage/overlay
mount | grep -q '/local/screencapt/local/portage/distfiles' || mount -o bind /local/portage/distfiles /local/screencapt/local/portage/distfiles

chroot /local/screencapt 


